---
title: "wk5"
author: "LU HAN"
date: "April 30, 2018"
output: html_document
---

```{r}
library(tidyverse)
library(skimr)
library(here)
library(geofacet)
```

```{r}
acs <- read_csv(here("data", "acs2015_county_data.csv")) %>% 
  rename(fips = CensusId) %>% 
  janitor::clean_names()

food <- readxl::read_xlsx(here("data", "DataDownload.xlsx"),
                          sheet = 5) %>% 
  janitor::clean_names() %>% 
  select(fips, pct_laccess_pop15) %>% 
  mutate(fips = as.numeric(fips))

us_grid <- us_state
```

```{r}
access <- inner_join(acs, food, by = "fips") %>% glimpse()

plot <- access %>% 
  ggplot(aes(x = log(income_per_cap), y = pct_laccess_pop15)) +
  scale_x_continuous(breaks = seq(9, 11, by = 1)) +
  geom_point()+
  facet_geo(~ state, grid = "us_state_grid3") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0)) +
  labs(title = "2015 Percentage of Population with Low Access to Store by Income per Captita: by County & State ",
       subtitle = "",
       y = "% of population with low access to store(s)",
       x = "Income per Capita (log scale)",
       caption = "design is inspired by Graham Tierney, income data from American Community Survey, Food Access data from Food Environment Atlas data download")
 
ggsave("us_food_access_by_county.png", width = 14, height = 7.5)
  
```